/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package misc.java;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class MainTest {
  @Test
  void testSomething() {
    assertEquals(1, 1);
  }
}
